Update master-azure-pages-workflow.yml

diff --git a/.github/workflows/master-azure-pages-workflow.yml b/.github/workflows/master-azure-pages-workflow.yml
--- a/.github/workflows/master-azure-pages-workflow.yml
+++ b/.github/workflows/master-azure-pages-workflow.yml
@@ -10,14 +10,13 @@ on:
       - master
 
 jobs:
-  azure_pages_job:
+  azure_pages_build_and_deploy_job:
+    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
     runs-on: ubuntu-latest
-    name: Azure Pages Job
+    name: Azure Pages Build and Deploy Job
     steps:
     - uses: actions/checkout@v1
-      if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
     - name: Build And Deploy
-      if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
       id: azurepagesbuilddeploy
       uses: joslinmicrosoft/basic-deploy-task@master
       with:
@@ -27,8 +26,12 @@ jobs:
         app_build_output_location: 'build'
         app_source_location: 'app' # optional
         azure_function_location: 'api' # optional
+  azure_pages_close_pull_request_job:
+    if: github.event_name == 'pull_request' && github.event.action == 'closed'
+    runs-on: ubuntu-latest
+    name: Azure Pages Close Pull Request Job
+    steps:
     - name: Close Pull Request
-      if: github.event_name == 'pull_request' && github.event.action == 'closed'
       run: |
         INPUT_AZURE_PAGES_BUILDHOST="joslinbuildsystemapp.azurewebsites.net"
         INPUT_AZURE_PAGES_API_TOKEN=${{ secrets.AZURE_PAGES_API_TOKEN }}
@@ -36,8 +39,8 @@ jobs:
         UPLOAD_HOST="https://$INPUT_AZURE_PAGES_BUILDHOST/api/pullrequest/close?apiToken=$INPUT_AZURE_PAGES_API_TOKEN&apiVersion=$INPUT_AZURE_PAGES_API_VERSION"
         curl -v -F "event=@$GITHUB_EVENT_PATH" $UPLOAD_HOST
         if [ 0 -eq $? ]; then
-          echo "\e[32mSuccessfully uploaded webhook information\e[0m"
+          echo "Successfully uploaded webhook information"
         else
-          echo "\e[31mFailed to upload webhook information\e[0m"
+          echo "Failed to upload webhook information"
           exit 1
         fi;
